### ISSUE TITLE
Cannot use "annotationProcessor "com.github.Anuken:jabel:$jabelVersion"

### ISSUE THREAD

**Issue by liplum** [Anuken/MindustryJavaModTemplate#12]
IDEA 2021.3 , Java 17.0.2
If I use this line in build.gradle it will raise a expetion when run task "compileJava" (or just "jar").
`java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider com.github.bsideup.jabel.JabelCompilerPlugin could not be instantiated`
So I comment that line in "dependencies" function call and it does work.
Please fix it.

**Comment by Anuken** [comment]
1. That's not the whole error message, run with `--stacktrace`.
2. Looks like a local problem, the [CI](https://github.com/Anuken/MindustryJavaModTemplate/runs/4953026779) passes fine with Java 17.

**Comment by liplum** [comment]
1.The Whole error message about 'jar --stacktrac' is on https://pastebin.ubuntu.com/p/DnXWRzsJ3v/. This time , I've taken an advice from Mindustry Discord#java and used JDK 16
2.Sorry. It's my first time to participate in modding in Mindustry ,so I don't know what's the CI.

**Comment by Anuken** [comment]
I'm not sure what's causing the error. I've updated the libraries for jabel, which may fix the problem.

CI is Continuous Integration - it's a system that automatically builds this repository every commit to check for errors. It runs (and succeeds) with Java 17, which implies that the problem you're experiencing is not something inherently caused by Java 17.

**Comment by liplum** [comment]
Thank for your help.
Even though I destory my gradle repository "%APPDATA%/.gradle"  and re-init the project in the latest one, it still doesn't work and shows the same error.
Then I tested that on my laptop, unfortunately, it showed "Execution failed for task ':compileJava'.invalid flag: --release". It's weired because I've really used JDK 17 on my laptop while it seems like that it will only happen on JDK 8 and lower.
Come back to the title, that's the only work around which keeps me coding(By the way. I have another project before this. In that peoject, I use Sonnicon/mindustry-modtemplate and JDK 8 as well as it does work. And I' going to use your template because a member in discord said his was outdated and I needed to use yours.).
I guess it may be my problem but I won't give up and will try to test it on my firend.

**Comment by Anuken** [comment]
If JDK 16 works, you should use that.

> it showed "Execution failed for task ':compileJava'.invalid flag: --release"

Make sure you don't have Java 8 installed - JAVA_HOME should be set to the JDK 16/17 directory, and `java --version` should print 17/16.

**Comment by liplum** [comment]
Thank you for your reminder. I forgot that because I seldom use my laptop. Well, I modified the environment path and made sure the cmd prints "java 16" on both desktop and laptop.
And now, my laptop has been also blocked at the same stage as my desktop --"Provider com.github.bsideup.jabel.JabelCompilerPlugin could not be instantiated"
So I suspect it may be caused by my network beacuse it's only thing similiar on my two PCs.
There's another thing that only one package "mindustry.annotations.Annotations" cannot be found on both my projects(one template from you and one from Sonnicon). What's the effect of losing it?
Now I have to comment that line ("annotationProcessor "com.github.Anuken:jabel:$jabelVersion") . It's only way I can do.

**Comment by liplum** [comment]
It the same happens on my friend(IDEA 2021.3 JDK 16) and this's the first time he has installed the IDEA. This is his error info: https://pastebin.ubuntu.com/p/JPm34DMy3w/
Despite the text encoding error, can it prove it isn't an isolated problem and it may happen on others?
Or causing by the latest IDEA version?

**Comment by liplum** [comment]
I and my friend ran the tasks (not all, only "init" and "jar") only through IntelliJ.

**Comment by Anuken** [comment]
I still don't know what the problem is, but it continues to occur to other people, so I've commented out Jabel and left it as an optional step for "advanced" users to try, if they want.

**Comment by Zelaux** [comment]
I added ```compileJava.options.fork = true``` above ```dependencies``` block and it worked for me

**Comment by buthed010203** [comment]
You shouldn't need to fork at all now, just use `annotationProcessor 'com.github.Anuken:jabel:f88d3273ba'` instead of what was there previously
