### ISSUE TITLE
upgrade to newer jdk version

### ISSUE THREAD

**Issue by TheEE145** [Anuken/MindustryJavaModTemplate#14]
upgrade to newer jdk version (for example, jdk 8+) 
because jdk7 is closed for public (deleted from world) 
and modding is impossible for new players in mindustry. 

you have jdk 7.

**Comment by Anuken** [comment]
> you have jdk 7.

No, I don't, you must be confusing that with JDK 17. This template won't even function with Java 8, let alone 7.
