### ISSUE TITLE
YouTube link video guide how to start on Windows / Mac

### ISSUE THREAD

**Issue by CoCuCoH41k** [Anuken/MindustryJavaModTemplate#20]
Yes

**Comment by CoCuCoH41k** [comment]
![image](https://user-images.githubusercontent.com/70099291/221861078-7cac5b58-6a49-4fb8-b15e-2c3386cf39fb.png)

And explain how

**Comment by Slotterleet** [comment]
> Если вы уверены в надежности команды, введите ".\gradlew".

Have you considered reading what's on the terminal?
`.\gradlew jar`
